package enum

import (
	"strings"
)

// MySQL保留字
var MYSQL_RESERVED_WORDS = func() map[string]Token {
	m := make(map[string]Token)
	for k, v := range RESERVED_WORDS {
		m[k] = v
	}
	add := func(t Token) {
		m[strings.ToUpper(t.Sql)] = t
	}
	add(Tokens.LIMIT)
	add(Tokens.HIGHP_RIORITY)
	add(Tokens.STRAIGHT_JOIN)
	add(Tokens.SQL_SMALL_RESULT)
	add(Tokens.SQL_BIG_RESULT)
	add(Tokens.SQL_CALC_FOUND_ROWS)
	add(Tokens.DISTINCTROW)
	add(Tokens.LEADING)
	add(Tokens.BOTH)
	add(Tokens.TRAILING)
	add(Tokens.CHARACTER)
	add(Tokens.UNSIGNED)
	add(Tokens.TRUE)
	add(Tokens.FALSE)
	add(Tokens.REGEXP)
	add(Tokens.R_LIKE)
	add(Tokens.XOR)
	add(Tokens.ASC)
	add(Tokens.DESC)
	add(Tokens.DIV)
	add(Tokens.MOD)
	add(Tokens.INTERVAL)
	add(Tokens.LOW_PRIORITY)
	add(Tokens.IGNORE)
	add(Tokens.FORCE)
	add(Tokens.PARTITION)
	add(Tokens.DELAYED)
	add(Tokens.KEY)
	add(Tokens.ZEROFILL)
	add(Tokens.SECOND_MICROSECOND)
	add(Tokens.MINUTE_MICROSECOND)
	add(Tokens.MINUTESECOND)
	add(Tokens.HOUR_MICROSECOND)
	add(Tokens.HOUR_SECOND)
	add(Tokens.HOUR_MINUTE)
	add(Tokens.DAY_MICROSECOND)
	add(Tokens.DAY_SECOND)
	add(Tokens.DAY_MINUTE)
	add(Tokens.DAY_HOUR)
	add(Tokens.YEAR_MONTH)
	add(Tokens.SEPARATOR)
	add(Tokens.PROCEDURE)
	add(Tokens.INT1)
	add(Tokens.INT2)
	add(Tokens.INT3)
	add(Tokens.INT4)
	add(Tokens.INT8)
	add(Tokens.INTEGER)
	add(Tokens.TINYINT)
	add(Tokens.SMALLINT)
	add(Tokens.MEDIUMINT)
	add(Tokens.INT)
	add(Tokens.BIGINT)
	add(Tokens.FLOAT)
	add(Tokens.FLOAT4)
	add(Tokens.FLOAT8)
	add(Tokens.DOUBLE)
	add(Tokens.DECIMAL)
	add(Tokens.VARCHAR)
	add(Tokens.CHAR)
	add(Tokens.BINARY)
	add(Tokens.VARBINARY)
	add(Tokens.TINYTEXT)
	add(Tokens.MEDIUMTEXT)
	add(Tokens.LONGTEXT)
	add(Tokens.BLOB)
	add(Tokens.TINYBLOB)
	add(Tokens.MEDIUMBLOB)
	add(Tokens.LONGBLOB)
	add(Tokens.EXCEPT)
	add(Tokens.INTERSECT)
	add(Tokens.OVER)
	add(Tokens.WINDOW)
	add(Tokens.RANGE)
	add(Tokens.COLLATE)
	return m
}()
