package enum

import (
	"strings"
)

// MySQL保留字
var MYSQL_RESERVED_WORDS = func() map[string]Token {
	m := make(map[string]Token)
	for k, v := range RESERVED_WORDS {
		m[k] = v
	}
	add := func(t Token) {
		m[strings.ToUpper(t.Sql)] = t
	}
	add(Token_.LIMIT)
	add(Token_.HIGHP_RIORITY)
	add(Token_.STRAIGHT_JOIN)
	add(Token_.SQL_SMALL_RESULT)
	add(Token_.SQL_BIG_RESULT)
	add(Token_.SQL_CALC_FOUND_ROWS)
	add(Token_.DISTINCTROW)
	add(Token_.LEADING)
	add(Token_.BOTH)
	add(Token_.TRAILING)
	add(Token_.CHARACTER)
	add(Token_.UNSIGNED)
	add(Token_.TRUE)
	add(Token_.FALSE)
	add(Token_.REGEXP)
	add(Token_.R_LIKE)
	add(Token_.XOR)
	add(Token_.ASC)
	add(Token_.DESC)
	add(Token_.DIV)
	add(Token_.MOD)
	add(Token_.INTERVAL)
	add(Token_.LOW_PRIORITY)
	add(Token_.IGNORE)
	add(Token_.FORCE)
	add(Token_.PARTITION)
	add(Token_.DELAYED)
	add(Token_.KEY)
	add(Token_.ZEROFILL)
	add(Token_.SECOND_MICROSECOND)
	add(Token_.MINUTE_MICROSECOND)
	add(Token_.MINUTESECOND)
	add(Token_.HOUR_MICROSECOND)
	add(Token_.HOUR_SECOND)
	add(Token_.HOUR_MINUTE)
	add(Token_.DAY_MICROSECOND)
	add(Token_.DAY_SECOND)
	add(Token_.DAY_MINUTE)
	add(Token_.DAY_HOUR)
	add(Token_.YEAR_MONTH)
	add(Token_.SEPARATOR)
	add(Token_.PROCEDURE)
	add(Token_.INT1)
	add(Token_.INT2)
	add(Token_.INT3)
	add(Token_.INT4)
	add(Token_.INT8)
	add(Token_.INTEGER)
	add(Token_.TINYINT)
	add(Token_.SMALLINT)
	add(Token_.MEDIUMINT)
	add(Token_.INT)
	add(Token_.BIGINT)
	add(Token_.FLOAT)
	add(Token_.FLOAT4)
	add(Token_.FLOAT8)
	add(Token_.DOUBLE)
	add(Token_.DECIMAL)
	add(Token_.VARCHAR)
	add(Token_.CHAR)
	add(Token_.BINARY)
	add(Token_.VARBINARY)
	add(Token_.TINYTEXT)
	add(Token_.MEDIUMTEXT)
	add(Token_.LONGTEXT)
	add(Token_.BLOB)
	add(Token_.TINYBLOB)
	add(Token_.MEDIUMBLOB)
	add(Token_.LONGBLOB)
	add(Token_.EXCEPT)
	add(Token_.INTERSECT)
	add(Token_.OVER)
	add(Token_.WINDOW)
	add(Token_.RANGE)
	add(Token_.COLLATE)
	return m
}()
