package enum

import o "github.com/jishaocong0910/go-object-util"

type MySqlBinaryOperator struct {
	*o.EnumElem__
	O BinaryOperator
	// 优先级，越小优先级越高
	Precedence int
}

type _MySqlBinaryOperator struct {
	*o.Enum__[MySqlBinaryOperator]
	JSON_EXTRACT,
	JSON_UNQUOTE,
	MEMBER_OF,
	COLLATE,
	BITWISE_XOR,
	MULTIPLY,
	DIVIDE,
	MODULUS,
	DIV,
	MOD,
	ADD,
	SUBTRACT,
	RIGHT_SHIFT,
	LEFT_SHIFT,
	BITWISE_AND,
	BITWISE_OR,
	EQUAL_OR_ASSIGNMENT,
	LESS_THAN_OR_EQUAL_OR_GREATER_THAN,
	GREATER_THAN,
	LESS_THAN,
	GREATER_THAN_OR_EQUAL,
	LESS_THAN_OR_EQUAL,
	LESS_THAN_OR_GREATER,
	NOT_EQUAL,
	IN,
	NOT_IN,
	IS,
	IS_NOT,
	LIKE,
	NOT_LIKE,
	SOUNDS_LIKE,
	REGEXP,
	NOT_REGEXP,
	RLIKE,
	NOT_RLIKE,
	BETWEEN,
	NOT_BETWEEN,
	BOOLEAN_AND,
	BOOLEAN_AND2,
	BOOLEAN_XOR,
	BOOLEAN_OR,
	BOOLEAN_OR2,
	ASSIGN MySqlBinaryOperator
}

var MySqlBinaryOperator_ = o.NewEnum[MySqlBinaryOperator](_MySqlBinaryOperator{
	JSON_EXTRACT:                       MySqlBinaryOperator{nil, BinaryOperator_.JSON_EXTRACT, 0},
	JSON_UNQUOTE:                       MySqlBinaryOperator{nil, BinaryOperator_.JSON_UNQUOTE, 0},
	MEMBER_OF:                          MySqlBinaryOperator{nil, BinaryOperator_.MEMBER_OF, 1},
	COLLATE:                            MySqlBinaryOperator{nil, BinaryOperator_.COLLATE, 1},
	BITWISE_XOR:                        MySqlBinaryOperator{nil, BinaryOperator_.BITWISE_XOR, 2},
	MULTIPLY:                           MySqlBinaryOperator{nil, BinaryOperator_.MULTIPLY, 3},
	DIVIDE:                             MySqlBinaryOperator{nil, BinaryOperator_.DIVIDE, 3},
	MODULUS:                            MySqlBinaryOperator{nil, BinaryOperator_.MODULUS, 3},
	DIV:                                MySqlBinaryOperator{nil, BinaryOperator_.DIV, 3},
	MOD:                                MySqlBinaryOperator{nil, BinaryOperator_.MOD, 3},
	ADD:                                MySqlBinaryOperator{nil, BinaryOperator_.ADD, 4},
	SUBTRACT:                           MySqlBinaryOperator{nil, BinaryOperator_.SUBTRACT, 4},
	RIGHT_SHIFT:                        MySqlBinaryOperator{nil, BinaryOperator_.RIGHT_SHIFT, 5},
	LEFT_SHIFT:                         MySqlBinaryOperator{nil, BinaryOperator_.LEFT_SHIFT, 5},
	BITWISE_AND:                        MySqlBinaryOperator{nil, BinaryOperator_.BITWISE_AND, 6},
	BITWISE_OR:                         MySqlBinaryOperator{nil, BinaryOperator_.BITWISE_OR, 7},
	EQUAL_OR_ASSIGNMENT:                MySqlBinaryOperator{nil, BinaryOperator_.EQUAL_OR_ASSIGNMENT, 8},
	LESS_THAN_OR_EQUAL_OR_GREATER_THAN: MySqlBinaryOperator{nil, BinaryOperator_.LESS_THAN_OR_EQUAL_OR_GREATER_THAN, 8},
	GREATER_THAN:                       MySqlBinaryOperator{nil, BinaryOperator_.GREATER_THAN, 8},
	LESS_THAN:                          MySqlBinaryOperator{nil, BinaryOperator_.LESS_THAN, 8},
	GREATER_THAN_OR_EQUAL:              MySqlBinaryOperator{nil, BinaryOperator_.GREATER_THAN_OR_EQUAL, 8},
	LESS_THAN_OR_EQUAL:                 MySqlBinaryOperator{nil, BinaryOperator_.LESS_THAN_OR_EQUAL, 8},
	LESS_THAN_OR_GREATER:               MySqlBinaryOperator{nil, BinaryOperator_.LESS_THAN_OR_GREATER, 8},
	NOT_EQUAL:                          MySqlBinaryOperator{nil, BinaryOperator_.NOT_EQUAL, 8},
	IN:                                 MySqlBinaryOperator{nil, BinaryOperator_.IN, 8},
	NOT_IN:                             MySqlBinaryOperator{nil, BinaryOperator_.NOT_IN, 8},
	IS:                                 MySqlBinaryOperator{nil, BinaryOperator_.IS, 8},
	IS_NOT:                             MySqlBinaryOperator{nil, BinaryOperator_.IS_NOT, 8},
	LIKE:                               MySqlBinaryOperator{nil, BinaryOperator_.LIKE, 8},
	NOT_LIKE:                           MySqlBinaryOperator{nil, BinaryOperator_.NOT_LIKE, 8},
	SOUNDS_LIKE:                        MySqlBinaryOperator{nil, BinaryOperator_.SOUNDS_LIKE, 8},
	REGEXP:                             MySqlBinaryOperator{nil, BinaryOperator_.REGEXP, 8},
	NOT_REGEXP:                         MySqlBinaryOperator{nil, BinaryOperator_.NOT_REGEXP, 8},
	RLIKE:                              MySqlBinaryOperator{nil, BinaryOperator_.RLIKE, 8},
	NOT_RLIKE:                          MySqlBinaryOperator{nil, BinaryOperator_.NOT_RLIKE, 8},
	BETWEEN:                            MySqlBinaryOperator{nil, BinaryOperator_.BETWEEN, 9},
	NOT_BETWEEN:                        MySqlBinaryOperator{nil, BinaryOperator_.NOT_BETWEEN, 9},
	BOOLEAN_AND:                        MySqlBinaryOperator{nil, BinaryOperator_.BOOLEAN_AND, 10},
	BOOLEAN_AND2:                       MySqlBinaryOperator{nil, BinaryOperator_.BOOLEAN_AND2, 10},
	BOOLEAN_XOR:                        MySqlBinaryOperator{nil, BinaryOperator_.BOOLEAN_XOR, 11},
	BOOLEAN_OR:                         MySqlBinaryOperator{nil, BinaryOperator_.BOOLEAN_OR, 12},
	BOOLEAN_OR2:                        MySqlBinaryOperator{nil, BinaryOperator_.BOOLEAN_OR2, 12},
	ASSIGN:                             MySqlBinaryOperator{nil, BinaryOperator_.ASSIGN, 13},
})
