package enum

import "strings"

// 公共保留字
var RESERVED_WORDS = func() map[string]Token {
	m := make(map[string]Token)
	add := func(t Token) {
		m[strings.ToUpper(t.Sql)] = t
	}
	add(Token_.ALL)
	add(Token_.SELECT)
	add(Token_.INSERT)
	add(Token_.UPDATE)
	add(Token_.DELETE)
	add(Token_.ALTER)
	add(Token_.CREATE)
	add(Token_.CASE)
	add(Token_.WHEN)
	add(Token_.THEN)
	add(Token_.ELSE)
	add(Token_.DISTINCT)
	add(Token_.VALUES)
	add(Token_.TABLE)
	add(Token_.ROW)
	add(Token_.ROWS)
	add(Token_.AS)
	add(Token_.FROM)
	add(Token_.CROSS)
	add(Token_.INNER)
	add(Token_.LEFT)
	add(Token_.RIGHT)
	add(Token_.NATURAL)
	add(Token_.OUTER)
	add(Token_.JOIN)
	add(Token_.ON)
	add(Token_.USING)
	add(Token_.USE)
	add(Token_.INDEX)
	add(Token_.KEY)
	add(Token_.FOR)
	add(Token_.ORDER)
	add(Token_.GROUP)
	add(Token_.BY)
	add(Token_.WHERE)
	add(Token_.SET)
	add(Token_.DECIMAL)
	add(Token_.LOCK)
	add(Token_.IN)
	add(Token_.WITH)
	add(Token_.AND)
	add(Token_.IS)
	add(Token_.NOT)
	add(Token_.LIKE)
	add(Token_.NULL)
	add(Token_.OR)
	add(Token_.HAVING)
	add(Token_.UNION)
	add(Token_.INTO)
	add(Token_.BETWEEN)
	add(Token_.EXISTS)
	add(Token_.CHAR)
	add(Token_.OF)
	add(Token_.DEFAULT)
	add(Token_.DUAL)
	return m
}()
