package enum

import "strings"

// 公共保留字
var RESERVED_WORDS = func() map[string]Token {
	m := make(map[string]Token)
	add := func(t Token) {
		m[strings.ToUpper(t.Sql)] = t
	}
	add(Tokens.ALL)
	add(Tokens.SELECT)
	add(Tokens.INSERT)
	add(Tokens.UPDATE)
	add(Tokens.DELETE)
	add(Tokens.ALTER)
	add(Tokens.CREATE)
	add(Tokens.CASE)
	add(Tokens.WHEN)
	add(Tokens.THEN)
	add(Tokens.ELSE)
	add(Tokens.DISTINCT)
	add(Tokens.VALUES)
	add(Tokens.TABLE)
	add(Tokens.ROW)
	add(Tokens.ROWS)
	add(Tokens.AS)
	add(Tokens.FROM)
	add(Tokens.CROSS)
	add(Tokens.INNER)
	add(Tokens.LEFT)
	add(Tokens.RIGHT)
	add(Tokens.NATURAL)
	add(Tokens.OUTER)
	add(Tokens.JOIN)
	add(Tokens.ON)
	add(Tokens.USING)
	add(Tokens.USE)
	add(Tokens.INDEX)
	add(Tokens.KEY)
	add(Tokens.FOR)
	add(Tokens.ORDER)
	add(Tokens.GROUP)
	add(Tokens.BY)
	add(Tokens.WHERE)
	add(Tokens.SET)
	add(Tokens.DECIMAL)
	add(Tokens.LOCK)
	add(Tokens.IN)
	add(Tokens.WITH)
	add(Tokens.AND)
	add(Tokens.IS)
	add(Tokens.NOT)
	add(Tokens.LIKE)
	add(Tokens.NULL)
	add(Tokens.OR)
	add(Tokens.HAVING)
	add(Tokens.UNION)
	add(Tokens.INTO)
	add(Tokens.BETWEEN)
	add(Tokens.EXISTS)
	add(Tokens.CHAR)
	add(Tokens.OF)
	add(Tokens.DEFAULT)
	add(Tokens.DUAL)
	return m
}()
